### PR TITLE
Fix typos all around

### PR DESCRIPTION
**Pull request by szepeviktor**
@thomasdiluccio This is for you.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Please consider using these in CI.

1. typos
2. sphinx-lint

https://github.com/szepeviktor/byte-level-care/tree/master/.github/workflows

**Comment by thomasdiluccio** [comment]
Oh dear ....  Thanks a lot @szepeviktor!
I'll backport your PR within our mono repo and keep you posted.
I'm also pinging the team for adding those tools in our CI.

**Comment by thomasdiluccio** [comment]
Hi @szepeviktor!
I backported your suggestion to our monorepo. Could you please update your branch to ensure I haven't forgotten anything?

**Comment by szepeviktor** [comment]
Everything is all right.

**Comment by thomasdiluccio** [comment]
Thanks @szepeviktor

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request closed without merging**
